apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devopschart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /wallet
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "devopschart.fullname" . }}-core
            port:
              number: {{ .Values.core.servicePort }}
