apiVersion: v1
kind: Service
metadata:
  name: {{ include "devopschart.fullname" . }}-core
  labels:
    {{- include "devopschart.core.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "devopschart.core.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.core.servicePort }}
      targetPort: {{ .Values.core.containerPort }}