apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devopschart.fullname" . }}-pg
  labels:
    {{- include "devopschart.pg.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "devopschart.pg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devopschart.pg.labels" . | nindent 4 }}
    spec:
      containers:
        - name: {{ include "devopschart.fullname" . }}-pg
          image: "{{ .Values.pg.image.repository }}:{{ .Values.pg.image.tag}}"
          ports:
            - containerPort: {{ .Values.pg.containerPort }}
          envFrom:
            - secretRef:
                name: {{ include "devopschart.fullname" . }}-pg
