apiVersion: v1
kind: Service
metadata:
  name: {{ include "devopschart.fullname" . }}-pg
  labels:
    {{- include "devopschart.pg.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "devopschart.pg.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.pg.servicePort }}
      targetPort: {{ .Values.pg.containerPort }}