name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint:
      name: "Linting"
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Install requirements
          run: pip install -r requirements.txt

        - name: Check linter issues
          run: ruff check .
        - name: Check formatter issues
          run: ruff format .
        - name: Typechecking
          run: mypy .

  verify_migrations:
      name: "Verifying migrations"
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Testing
          run: docker-compose -f ./infra/docker/ci/docker-compose-updown.yml up --build --abort-on-container-exit --exit-code-from migrations
          shell: bash

  test:
    name: "Testing"
    runs-on: ubuntu-latest
    needs: [lint, verify_migrations]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Setup database
        run: docker-compose -f ./infra/docker/ci/docker-compose-tests.yml up -d --build
        shell: bash

      - name: Setup config
        run: cp ./infra/docker/ci/.env.tests ./etc/.env.tests

      - name: Test
        run: CONFIG_NAME=".env.tests" pytest tests -vvv
